// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_acdfg.proto

#ifndef PROTOBUF_proto_5facdfg_2eproto__INCLUDED
#define PROTOBUF_proto_5facdfg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace edu {
namespace colorado {
namespace plv {
namespace fixr {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_5facdfg_2eproto();
void protobuf_AssignDesc_proto_5facdfg_2eproto();
void protobuf_ShutdownFile_proto_5facdfg_2eproto();

class Acdfg;
class Acdfg_DataNode;
class Acdfg_MiscNode;
class Acdfg_MethodNode;
class Acdfg_ControlEdge;
class Acdfg_DefEdge;
class Acdfg_UseEdge;

// ===================================================================

class Acdfg_DataNode : public ::google::protobuf::Message {
 public:
  Acdfg_DataNode();
  virtual ~Acdfg_DataNode();

  Acdfg_DataNode(const Acdfg_DataNode& from);

  inline Acdfg_DataNode& operator=(const Acdfg_DataNode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_DataNode& default_instance();

  void Swap(Acdfg_DataNode* other);

  // implements Message ----------------------------------------------

  Acdfg_DataNode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_DataNode& from);
  void MergeFrom(const Acdfg_DataNode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required string type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  inline void set_allocated_type(::std::string* type);

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::std::string* name_;
  ::std::string* type_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_DataNode* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg_MiscNode : public ::google::protobuf::Message {
 public:
  Acdfg_MiscNode();
  virtual ~Acdfg_MiscNode();

  Acdfg_MiscNode(const Acdfg_MiscNode& from);

  inline Acdfg_MiscNode& operator=(const Acdfg_MiscNode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_MiscNode& default_instance();

  void Swap(Acdfg_MiscNode* other);

  // implements Message ----------------------------------------------

  Acdfg_MiscNode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_MiscNode& from);
  void MergeFrom(const Acdfg_MiscNode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.MiscNode)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_MiscNode* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg_MethodNode : public ::google::protobuf::Message {
 public:
  Acdfg_MethodNode();
  virtual ~Acdfg_MethodNode();

  Acdfg_MethodNode(const Acdfg_MethodNode& from);

  inline Acdfg_MethodNode& operator=(const Acdfg_MethodNode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_MethodNode& default_instance();

  void Swap(Acdfg_MethodNode* other);

  // implements Message ----------------------------------------------

  Acdfg_MethodNode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_MethodNode& from);
  void MergeFrom(const Acdfg_MethodNode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional uint64 invokee = 2;
  inline bool has_invokee() const;
  inline void clear_invokee();
  static const int kInvokeeFieldNumber = 2;
  inline ::google::protobuf::uint64 invokee() const;
  inline void set_invokee(::google::protobuf::uint64 value);

  // required string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated uint64 argument = 4;
  inline int argument_size() const;
  inline void clear_argument();
  static const int kArgumentFieldNumber = 4;
  inline ::google::protobuf::uint64 argument(int index) const;
  inline void set_argument(int index, ::google::protobuf::uint64 value);
  inline void add_argument(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      argument() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_argument();

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_invokee();
  inline void clear_has_invokee();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 invokee_;
  ::std::string* name_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > argument_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_MethodNode* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg_ControlEdge : public ::google::protobuf::Message {
 public:
  Acdfg_ControlEdge();
  virtual ~Acdfg_ControlEdge();

  Acdfg_ControlEdge(const Acdfg_ControlEdge& from);

  inline Acdfg_ControlEdge& operator=(const Acdfg_ControlEdge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_ControlEdge& default_instance();

  void Swap(Acdfg_ControlEdge* other);

  // implements Message ----------------------------------------------

  Acdfg_ControlEdge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_ControlEdge& from);
  void MergeFrom(const Acdfg_ControlEdge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // required uint64 from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline ::google::protobuf::uint64 from() const;
  inline void set_from(::google::protobuf::uint64 value);

  // required uint64 to = 3;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 3;
  inline ::google::protobuf::uint64 to() const;
  inline void set_to(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_to();
  inline void clear_has_to();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 to_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_ControlEdge* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg_DefEdge : public ::google::protobuf::Message {
 public:
  Acdfg_DefEdge();
  virtual ~Acdfg_DefEdge();

  Acdfg_DefEdge(const Acdfg_DefEdge& from);

  inline Acdfg_DefEdge& operator=(const Acdfg_DefEdge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_DefEdge& default_instance();

  void Swap(Acdfg_DefEdge* other);

  // implements Message ----------------------------------------------

  Acdfg_DefEdge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_DefEdge& from);
  void MergeFrom(const Acdfg_DefEdge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // required uint64 from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline ::google::protobuf::uint64 from() const;
  inline void set_from(::google::protobuf::uint64 value);

  // required uint64 to = 3;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 3;
  inline ::google::protobuf::uint64 to() const;
  inline void set_to(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_to();
  inline void clear_has_to();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 to_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_DefEdge* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg_UseEdge : public ::google::protobuf::Message {
 public:
  Acdfg_UseEdge();
  virtual ~Acdfg_UseEdge();

  Acdfg_UseEdge(const Acdfg_UseEdge& from);

  inline Acdfg_UseEdge& operator=(const Acdfg_UseEdge& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg_UseEdge& default_instance();

  void Swap(Acdfg_UseEdge* other);

  // implements Message ----------------------------------------------

  Acdfg_UseEdge* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg_UseEdge& from);
  void MergeFrom(const Acdfg_UseEdge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // required uint64 from = 2;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 2;
  inline ::google::protobuf::uint64 from() const;
  inline void set_from(::google::protobuf::uint64 value);

  // required uint64 to = 3;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 3;
  inline ::google::protobuf::uint64 to() const;
  inline void set_to(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_to();
  inline void clear_has_to();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 to_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg_UseEdge* default_instance_;
};
// -------------------------------------------------------------------

class Acdfg : public ::google::protobuf::Message {
 public:
  Acdfg();
  virtual ~Acdfg();

  Acdfg(const Acdfg& from);

  inline Acdfg& operator=(const Acdfg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Acdfg& default_instance();

  void Swap(Acdfg* other);

  // implements Message ----------------------------------------------

  Acdfg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Acdfg& from);
  void MergeFrom(const Acdfg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Acdfg_DataNode DataNode;
  typedef Acdfg_MiscNode MiscNode;
  typedef Acdfg_MethodNode MethodNode;
  typedef Acdfg_ControlEdge ControlEdge;
  typedef Acdfg_DefEdge DefEdge;
  typedef Acdfg_UseEdge UseEdge;

  // accessors -------------------------------------------------------

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.DataNode data_node = 1;
  inline int data_node_size() const;
  inline void clear_data_node();
  static const int kDataNodeFieldNumber = 1;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode& data_node(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode* mutable_data_node(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode* add_data_node();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode >&
      data_node() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode >*
      mutable_data_node();

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.MiscNode misc_node = 2;
  inline int misc_node_size() const;
  inline void clear_misc_node();
  static const int kMiscNodeFieldNumber = 2;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode& misc_node(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode* mutable_misc_node(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode* add_misc_node();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode >&
      misc_node() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode >*
      mutable_misc_node();

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode method_node = 3;
  inline int method_node_size() const;
  inline void clear_method_node();
  static const int kMethodNodeFieldNumber = 3;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode& method_node(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode* mutable_method_node(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode* add_method_node();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode >&
      method_node() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode >*
      mutable_method_node();

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge control_edge = 4;
  inline int control_edge_size() const;
  inline void clear_control_edge();
  static const int kControlEdgeFieldNumber = 4;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge& control_edge(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge* mutable_control_edge(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge* add_control_edge();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge >&
      control_edge() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge >*
      mutable_control_edge();

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge def_edge = 5;
  inline int def_edge_size() const;
  inline void clear_def_edge();
  static const int kDefEdgeFieldNumber = 5;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge& def_edge(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge* mutable_def_edge(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge* add_def_edge();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge >&
      def_edge() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge >*
      mutable_def_edge();

  // repeated .edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge use_edge = 6;
  inline int use_edge_size() const;
  inline void clear_use_edge();
  static const int kUseEdgeFieldNumber = 6;
  inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge& use_edge(int index) const;
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge* mutable_use_edge(int index);
  inline ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge* add_use_edge();
  inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge >&
      use_edge() const;
  inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge >*
      mutable_use_edge();

  // @@protoc_insertion_point(class_scope:edu.colorado.plv.fixr.protobuf.Acdfg)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode > data_node_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode > misc_node_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode > method_node_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge > control_edge_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge > def_edge_;
  ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge > use_edge_;
  friend void  protobuf_AddDesc_proto_5facdfg_2eproto();
  friend void protobuf_AssignDesc_proto_5facdfg_2eproto();
  friend void protobuf_ShutdownFile_proto_5facdfg_2eproto();

  void InitAsDefaultInstance();
  static Acdfg* default_instance_;
};
// ===================================================================


// ===================================================================

// Acdfg_DataNode

// required uint64 id = 1;
inline bool Acdfg_DataNode::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_DataNode::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_DataNode::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_DataNode::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_DataNode::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.id)
  return id_;
}
inline void Acdfg_DataNode::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.id)
}

// required string name = 2;
inline bool Acdfg_DataNode::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Acdfg_DataNode::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Acdfg_DataNode::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Acdfg_DataNode::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Acdfg_DataNode::name() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
  return *name_;
}
inline void Acdfg_DataNode::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
}
inline void Acdfg_DataNode::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
}
inline void Acdfg_DataNode::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
}
inline ::std::string* Acdfg_DataNode::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
  return name_;
}
inline ::std::string* Acdfg_DataNode::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Acdfg_DataNode::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.name)
}

// required string type = 3;
inline bool Acdfg_DataNode::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Acdfg_DataNode::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Acdfg_DataNode::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Acdfg_DataNode::clear_type() {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& Acdfg_DataNode::type() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
  return *type_;
}
inline void Acdfg_DataNode::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
}
inline void Acdfg_DataNode::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set_char:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
}
inline void Acdfg_DataNode::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
}
inline ::std::string* Acdfg_DataNode::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
  return type_;
}
inline ::std::string* Acdfg_DataNode::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Acdfg_DataNode::set_allocated_type(::std::string* type) {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (type) {
    set_has_type();
    type_ = type;
  } else {
    clear_has_type();
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:edu.colorado.plv.fixr.protobuf.Acdfg.DataNode.type)
}

// -------------------------------------------------------------------

// Acdfg_MiscNode

// required uint64 id = 1;
inline bool Acdfg_MiscNode::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_MiscNode::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_MiscNode::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_MiscNode::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_MiscNode::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.MiscNode.id)
  return id_;
}
inline void Acdfg_MiscNode::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.MiscNode.id)
}

// -------------------------------------------------------------------

// Acdfg_MethodNode

// required uint64 id = 1;
inline bool Acdfg_MethodNode::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_MethodNode::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_MethodNode::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_MethodNode::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_MethodNode::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.id)
  return id_;
}
inline void Acdfg_MethodNode::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.id)
}

// optional uint64 invokee = 2;
inline bool Acdfg_MethodNode::has_invokee() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Acdfg_MethodNode::set_has_invokee() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Acdfg_MethodNode::clear_has_invokee() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Acdfg_MethodNode::clear_invokee() {
  invokee_ = GOOGLE_ULONGLONG(0);
  clear_has_invokee();
}
inline ::google::protobuf::uint64 Acdfg_MethodNode::invokee() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.invokee)
  return invokee_;
}
inline void Acdfg_MethodNode::set_invokee(::google::protobuf::uint64 value) {
  set_has_invokee();
  invokee_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.invokee)
}

// required string name = 3;
inline bool Acdfg_MethodNode::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Acdfg_MethodNode::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Acdfg_MethodNode::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Acdfg_MethodNode::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Acdfg_MethodNode::name() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
  return *name_;
}
inline void Acdfg_MethodNode::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
}
inline void Acdfg_MethodNode::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
}
inline void Acdfg_MethodNode::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
}
inline ::std::string* Acdfg_MethodNode::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
  return name_;
}
inline ::std::string* Acdfg_MethodNode::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Acdfg_MethodNode::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.name)
}

// repeated uint64 argument = 4;
inline int Acdfg_MethodNode::argument_size() const {
  return argument_.size();
}
inline void Acdfg_MethodNode::clear_argument() {
  argument_.Clear();
}
inline ::google::protobuf::uint64 Acdfg_MethodNode::argument(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.argument)
  return argument_.Get(index);
}
inline void Acdfg_MethodNode::set_argument(int index, ::google::protobuf::uint64 value) {
  argument_.Set(index, value);
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.argument)
}
inline void Acdfg_MethodNode::add_argument(::google::protobuf::uint64 value) {
  argument_.Add(value);
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.argument)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Acdfg_MethodNode::argument() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.argument)
  return argument_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Acdfg_MethodNode::mutable_argument() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode.argument)
  return &argument_;
}

// -------------------------------------------------------------------

// Acdfg_ControlEdge

// required uint64 id = 1;
inline bool Acdfg_ControlEdge::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_ControlEdge::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_ControlEdge::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_ControlEdge::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_ControlEdge::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.id)
  return id_;
}
inline void Acdfg_ControlEdge::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.id)
}

// required uint64 from = 2;
inline bool Acdfg_ControlEdge::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Acdfg_ControlEdge::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Acdfg_ControlEdge::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Acdfg_ControlEdge::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
  clear_has_from();
}
inline ::google::protobuf::uint64 Acdfg_ControlEdge::from() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.from)
  return from_;
}
inline void Acdfg_ControlEdge::set_from(::google::protobuf::uint64 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.from)
}

// required uint64 to = 3;
inline bool Acdfg_ControlEdge::has_to() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Acdfg_ControlEdge::set_has_to() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Acdfg_ControlEdge::clear_has_to() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Acdfg_ControlEdge::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
  clear_has_to();
}
inline ::google::protobuf::uint64 Acdfg_ControlEdge::to() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.to)
  return to_;
}
inline void Acdfg_ControlEdge::set_to(::google::protobuf::uint64 value) {
  set_has_to();
  to_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge.to)
}

// -------------------------------------------------------------------

// Acdfg_DefEdge

// required uint64 id = 1;
inline bool Acdfg_DefEdge::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_DefEdge::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_DefEdge::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_DefEdge::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_DefEdge::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.id)
  return id_;
}
inline void Acdfg_DefEdge::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.id)
}

// required uint64 from = 2;
inline bool Acdfg_DefEdge::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Acdfg_DefEdge::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Acdfg_DefEdge::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Acdfg_DefEdge::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
  clear_has_from();
}
inline ::google::protobuf::uint64 Acdfg_DefEdge::from() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.from)
  return from_;
}
inline void Acdfg_DefEdge::set_from(::google::protobuf::uint64 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.from)
}

// required uint64 to = 3;
inline bool Acdfg_DefEdge::has_to() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Acdfg_DefEdge::set_has_to() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Acdfg_DefEdge::clear_has_to() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Acdfg_DefEdge::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
  clear_has_to();
}
inline ::google::protobuf::uint64 Acdfg_DefEdge::to() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.to)
  return to_;
}
inline void Acdfg_DefEdge::set_to(::google::protobuf::uint64 value) {
  set_has_to();
  to_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge.to)
}

// -------------------------------------------------------------------

// Acdfg_UseEdge

// required uint64 id = 1;
inline bool Acdfg_UseEdge::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Acdfg_UseEdge::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Acdfg_UseEdge::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Acdfg_UseEdge::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 Acdfg_UseEdge::id() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.id)
  return id_;
}
inline void Acdfg_UseEdge::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.id)
}

// required uint64 from = 2;
inline bool Acdfg_UseEdge::has_from() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Acdfg_UseEdge::set_has_from() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Acdfg_UseEdge::clear_has_from() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Acdfg_UseEdge::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
  clear_has_from();
}
inline ::google::protobuf::uint64 Acdfg_UseEdge::from() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.from)
  return from_;
}
inline void Acdfg_UseEdge::set_from(::google::protobuf::uint64 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.from)
}

// required uint64 to = 3;
inline bool Acdfg_UseEdge::has_to() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Acdfg_UseEdge::set_has_to() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Acdfg_UseEdge::clear_has_to() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Acdfg_UseEdge::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
  clear_has_to();
}
inline ::google::protobuf::uint64 Acdfg_UseEdge::to() const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.to)
  return to_;
}
inline void Acdfg_UseEdge::set_to(::google::protobuf::uint64 value) {
  set_has_to();
  to_ = value;
  // @@protoc_insertion_point(field_set:edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge.to)
}

// -------------------------------------------------------------------

// Acdfg

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.DataNode data_node = 1;
inline int Acdfg::data_node_size() const {
  return data_node_.size();
}
inline void Acdfg::clear_data_node() {
  data_node_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode& Acdfg::data_node(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.data_node)
  return data_node_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode* Acdfg::mutable_data_node(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.data_node)
  return data_node_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode* Acdfg::add_data_node() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.data_node)
  return data_node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode >&
Acdfg::data_node() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.data_node)
  return data_node_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DataNode >*
Acdfg::mutable_data_node() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.data_node)
  return &data_node_;
}

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.MiscNode misc_node = 2;
inline int Acdfg::misc_node_size() const {
  return misc_node_.size();
}
inline void Acdfg::clear_misc_node() {
  misc_node_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode& Acdfg::misc_node(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.misc_node)
  return misc_node_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode* Acdfg::mutable_misc_node(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.misc_node)
  return misc_node_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode* Acdfg::add_misc_node() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.misc_node)
  return misc_node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode >&
Acdfg::misc_node() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.misc_node)
  return misc_node_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MiscNode >*
Acdfg::mutable_misc_node() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.misc_node)
  return &misc_node_;
}

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.MethodNode method_node = 3;
inline int Acdfg::method_node_size() const {
  return method_node_.size();
}
inline void Acdfg::clear_method_node() {
  method_node_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode& Acdfg::method_node(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.method_node)
  return method_node_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode* Acdfg::mutable_method_node(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.method_node)
  return method_node_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode* Acdfg::add_method_node() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.method_node)
  return method_node_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode >&
Acdfg::method_node() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.method_node)
  return method_node_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_MethodNode >*
Acdfg::mutable_method_node() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.method_node)
  return &method_node_;
}

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.ControlEdge control_edge = 4;
inline int Acdfg::control_edge_size() const {
  return control_edge_.size();
}
inline void Acdfg::clear_control_edge() {
  control_edge_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge& Acdfg::control_edge(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.control_edge)
  return control_edge_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge* Acdfg::mutable_control_edge(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.control_edge)
  return control_edge_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge* Acdfg::add_control_edge() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.control_edge)
  return control_edge_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge >&
Acdfg::control_edge() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.control_edge)
  return control_edge_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_ControlEdge >*
Acdfg::mutable_control_edge() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.control_edge)
  return &control_edge_;
}

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.DefEdge def_edge = 5;
inline int Acdfg::def_edge_size() const {
  return def_edge_.size();
}
inline void Acdfg::clear_def_edge() {
  def_edge_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge& Acdfg::def_edge(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.def_edge)
  return def_edge_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge* Acdfg::mutable_def_edge(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.def_edge)
  return def_edge_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge* Acdfg::add_def_edge() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.def_edge)
  return def_edge_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge >&
Acdfg::def_edge() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.def_edge)
  return def_edge_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_DefEdge >*
Acdfg::mutable_def_edge() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.def_edge)
  return &def_edge_;
}

// repeated .edu.colorado.plv.fixr.protobuf.Acdfg.UseEdge use_edge = 6;
inline int Acdfg::use_edge_size() const {
  return use_edge_.size();
}
inline void Acdfg::clear_use_edge() {
  use_edge_.Clear();
}
inline const ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge& Acdfg::use_edge(int index) const {
  // @@protoc_insertion_point(field_get:edu.colorado.plv.fixr.protobuf.Acdfg.use_edge)
  return use_edge_.Get(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge* Acdfg::mutable_use_edge(int index) {
  // @@protoc_insertion_point(field_mutable:edu.colorado.plv.fixr.protobuf.Acdfg.use_edge)
  return use_edge_.Mutable(index);
}
inline ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge* Acdfg::add_use_edge() {
  // @@protoc_insertion_point(field_add:edu.colorado.plv.fixr.protobuf.Acdfg.use_edge)
  return use_edge_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge >&
Acdfg::use_edge() const {
  // @@protoc_insertion_point(field_list:edu.colorado.plv.fixr.protobuf.Acdfg.use_edge)
  return use_edge_;
}
inline ::google::protobuf::RepeatedPtrField< ::edu::colorado::plv::fixr::protobuf::Acdfg_UseEdge >*
Acdfg::mutable_use_edge() {
  // @@protoc_insertion_point(field_mutable_list:edu.colorado.plv.fixr.protobuf.Acdfg.use_edge)
  return &use_edge_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace fixr
}  // namespace plv
}  // namespace colorado
}  // namespace edu

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5facdfg_2eproto__INCLUDED
